spring:
  data:
    cassandra:
      port: 9042
      contact-points: cassandra-seed-mikhienkov
      keyspace-name: mykeyspace
      schema-action: create_if_not_exists
      entity-base-package: com.example.cassandra.springbootcassandragallery.model